name: Auto Merge Branch2 - Sequential Extended

on:
  push:
    branches:
      - dev

jobs:
  auto_back_merge_dev_f1:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: Merge dev -> f1
        continue-on-error: true
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: f1
          message: Merge dev into f1
          github_token: ${{ secrets.GH_AUTO_MERGER }}

  auto_back_merge_dev_f2:
    runs-on: ubuntu-latest
    needs: auto_back_merge_dev_f1
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: Merge dev -> f2
        continue-on-error: true
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: f2
          message: Merge dev into f2
          github_token: ${{ secrets.GH_AUTO_MERGER }}

  auto_back_merge_dev_f3:
    runs-on: ubuntu-latest
    needs: auto_back_merge_dev_f2
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: Merge dev -> f3
        continue-on-error: true
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: f3
          message: Merge dev into f3
          github_token: ${{ secrets.GH_AUTO_MERGER }}

  auto_back_merge_dev_f4:
    runs-on: ubuntu-latest
    needs: auto_back_merge_dev_f3
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: Merge dev -> f4
        continue-on-error: true
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: f4
          message: Merge dev into f4
          github_token: ${{ secrets.GH_AUTO_MERGER }}

  auto_back_merge_dev_f5:
    runs-on: ubuntu-latest
    needs: auto_back_merge_dev_f4
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: Merge dev -> f5
        continue-on-error: true
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: f5
          message: Merge dev into f5
          github_token: ${{ secrets.GH_AUTO_MERGER }}

  auto_back_merge_dev_f6:
    runs-on: ubuntu-latest
    needs: auto_back_merge_dev_f5
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: Merge dev -> f6
        continue-on-error: true
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: f6
          message: Merge dev into f6
          github_token: ${{ secrets.GH_AUTO_MERGER }}

  auto_back_merge_dev_f7:
    runs-on: ubuntu-latest
    needs: auto_back_merge_dev_f6
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: Merge dev -> f7
        continue-on-error: true
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: f7
          message: Merge dev into f7
          github_token: ${{ secrets.GH_AUTO_MERGER }}