name: Auto Merge Branch2

on:
  push:
    branches:
      - dev

concurrency:
  group: merge-${{ github.repository }}
  cancel-in-progress: false

jobs:
  sequential_merges:
    name: Merge to ${{ matrix.branch }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    strategy:
      max-parallel: 1
      matrix:
        branch: ['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']
    
    steps:
      - uses: actions/checkout@v4

      - name: Merge dev -> ${{ matrix.branch }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: ${{ matrix.branch }}
          message: Merge dev into ${{ matrix.branch }}
          github_token: ${{ secrets.GH_AUTO_MERGER }}

      - name: Wait for deployment
        run: |
          echo "Waiting for ${{ matrix.branch }} deployment to complete..."
          sleep 300